; created using pewGBMusicConverter
; source: music_win.txt

Music_winSongData:
db $84, $1E, $02
db $00, $2A, $00
db $FD
db $FD
db $83, $1E, $02
db $00, $2A, $00
db $83, $1E, $02
db $00, $2A, $00
db $83, $1E, $02
db $00, $2A, $00
db $FD
db $FD
db $84, $20, $04
db $00, $2C, $00
db $FD
db $FD
db $83, $1C, $04
db $00, $28, $00
db $FD
db $FD
db $83, $20, $04
db $00, $2C, $00
db $FD
db $FD
db $82, $22, $06
db $00, $2E, $00
db $00, $22, $00
db $00, $2E, $00
db $00, $22, $00
db $00, $2E, $00
db $00, $22, $00
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $00, $1E, $00
db $00, $25, $00
db $81, $28, $00
db $00, $2A, $00
db $00, $31, $00
db $00, $34, $00
db $00, $36, $00
db $FE ; or FE
MUSIC_WIN_SPEED EQU 3 ;*16ms per step (2,5 * ticks / tempo) / 16,75
