; created using pewGBMusicConverter
; source: music_short.txt

Music_shortSongData:
db $81, $00, $00
db $83, $00, $01
db $83, $00, $00
db $81, $00, $00
db $82, $00, $04
db $00, $00, $01
db $FD
db $84, $00, $00
db $81, $00, $00
db $81, $00, $04
db $83, $00, $00
db $81, $00, $00
db $82, $00, $06
db $83, $00, $07
db $83, $00, $06
db $84, $00, $04
db $FF ; or FE
MUSIC_SHORT_SPEED EQU 20 ;*16ms per step (2,5 * ticks / tempo) / 16,75
