; created using pewGBMusicConverter
; source: MusicWin.txt

MusicWinSongData:
db $84, $1E, $0E
db $00, $2A, $00
db $FD
db $FD
db $83, $1E, $0E
db $00, $2A, $00
db $83, $1E, $0E
db $00, $2A, $00
db $83, $1E, $0E
db $00, $2A, $00
db $FD
db $FD
db $84, $20, $10
db $00, $2C, $00
db $FD
db $FD
db $83, $1C, $10
db $00, $28, $00
db $FD
db $FD
db $83, $20, $10
db $00, $2C, $00
db $FD
db $FD
db $82, $22, $12
db $00, $2E, $00
db $00, $22, $00
db $00, $2E, $00
db $00, $22, $00
db $00, $2E, $00
db $00, $22, $00
db $00, $2E, $00
db $00, $22, $00
db $FD
db $FD
db $FD
db $FD
db $FD
db $00, $1E, $00
db $00, $25, $00
db $81, $28, $00
db $00, $2A, $00
db $00, $31, $00
db $00, $34, $00
db $00, $36, $00
db $FE
MUSICWIN_SPEED EQU 3 ;*16ms per step (2,5 * ticks / tempo) / 16,75
