; created using pewGBMusicConverter
; source: music_intro.txt

Music_introSongData:
db $81, $00, $00
db $FD
db $FD
db $FD
db $82, $00, $00
db $FD
db $FD
db $FD
db $83, $00, $00
db $FD
db $FD
db $FD
db $84, $00, $00
db $FD
db $FD
db $FD
db $00, $01, $00
db $FD
db $FD
db $FD
db $00, $00, $01
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FF ; or FE
MUSIC_INTRO_SPEED EQU 20 ;*16ms per step (2,5 * ticks / tempo) / 16,75
