; created using pewGBMusicConverter
; source: MusicLost.txt

MusicLostSongData:
db $82, $24, $18
db $FD
db $83, $23, $17
db $FD
db $83, $22, $16
db $FD
db $82, $21, $17
db $FD
db $83, $20, $16
db $FD
db $83, $1F, $15
db $FD
db $82, $1E, $14
db $FD
db $00, $1F, $15
db $FD
db $83, $1E, $14
db $00, $1F, $15
db $83, $1E, $14
db $00, $1F, $15
db $83, $1E, $14
db $00, $1F, $15
db $83, $1E, $14
db $00, $1F, $15
db $83, $1E, $14
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $FD
db $82, $23, $00
db $00, $2F, $00
db $FE
MUSICLOST_SPEED EQU 3 ;*16ms per step (2,5 * ticks / tempo) / 16,75
